### ISSUE TITLE
rollowert (ch0003 -> odp0001) wird nicht mehr aktualisiert

### ISSUE THREAD

**Issue by TheSpirit** [mobilutz/ioBroker.freeathome#107]
seit ein paar Tagen kann ich zwar noch meine meine rollos per restful api ansteuern, aber wenn ich diese verfahre, wird der prozentwert, wie weit meine rollos geschlossen sind nicht mehr aktualisiert.
der wert ist in ch0003 und dann odp0001 dargestellt.
ich verwende schon im version 0.0.3 und hatte bis vor ein paar tagen auch keine probleme.
egal ob ich per rest api das rollo verfahre, oder per busch jäger free@home schalter. der wert wird nicht aktualisiert.

**Comment by mobilutz** [comment]
@TheSpirit ich habe auch seit ein paar Tagen Probleme mit dem Adapter. Ich habe bisher keine Zeit gefunden mir das genauer anzuschauen 🙁
Sobald ich Zeit finde, werde ich das analysieren und hoffentlich eine Lösung finden.

**Comment by TheSpirit** [comment]
Bei mir geht es jetzt wieder. Problem war, das es für  meine rolloaktoren ein Update gab. Jetzt laufen sie wieder.

**Comment by mobilutz** [comment]
> Bei mir geht es jetzt wieder. Problem war, das es für meine rolloaktoren ein Update gab. Jetzt laufen sie wieder.

👍  Ich schliesse das Ticket dann!
