### ISSUE TITLE
Think about repo checker

### ISSUE THREAD

**Issue by GermanBluefox** [mobilutz/ioBroker.freeathome#15]
https://adapter-check.iobroker.in/?q=https://github.com/mobilutz/iobroker.freeathome

![image](https://user-images.githubusercontent.com/4582016/72975874-d3420580-3dd1-11ea-9bc1-021ea620d8a3.png)

**Comment by mobilutz** [comment]
@GermanBluefox Thanks, I fixed almost everything.

**Comment by mobilutz** [comment]
Closing this, as there is another automated issue for this topic: #20
