### ISSUE TITLE
missing required property "common.type"

### ISSUE THREAD

**Issue by bergch** [mobilutz/ioBroker.freeathome#552]
Hi - when using the adapter my logfile is getting spammed by the following messages: 

freeathome.0 | 2022-11-30 17:51:19.806 | warn | Object of state "freeathome.0.ABB2A1694251.deviceId" is missing the required property "common.type"

The Adapter works fine and the values are updated correctly, but the log volume exceeds 500MB per day. 
It would be great if this could be fixed.

And great work - keep on ;)

**Comment by mobilutz** [comment]
@bergch What version of the adapter are you running?

The `common.type` was added just a couple of day ago in v0.0.12, and now the adapter is at v0.0.17 https://www.npmjs.com/package/iobroker.freeathome

And thanks for the appreciation.

**Comment by bergch** [comment]
Hi, iam running v0.0.17 of the Adapter. The SynAP ist running at v2.6.4.

Regards Christoph

**Comment by mobilutz** [comment]
Ah the problem is, that the content was created already.

The only way (that I now know) is to remove the adapter and add it again.

Sorry about that
