### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by mabasger** [mobilutz/ioBroker.freeathome#56]
**Describe the bug**  
Adapter is starting, but it seems the connection to the free@home access point fails.

**To Reproduce**  
1. Install latest iobroker (3.7.8)
2. npm 8.16.0
3. freeathome from github
4. Create User with Configuration rights on the free@home access point
5. enter free@home access point IP and user in the configuration of the freeathome adapter
6. start the freeathome adapter
7. read the logs / object state (connection = false)

**Expected behavior**  
Devices in iobroker available

**Screenshots & Logfiles**  
`

host.homeserver | 2020-03-31 09:11:05.806 | error | Caught by controller[1]: (node:4319) UnhandledPromiseRejectionWarning:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by r
-- | -- | -- | --
host.homeserver | 2020-03-31 09:11:05.806 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:189:7)
host.homeserver | 2020-03-31 09:11:05.806 | error | Caught by controller[1]:     at <anonymous>
host.homeserver | 2020-03-31 09:11:05.806 | error | Caught by controller[1]:     at Freeathome.registerAllDevices (/opt/iobroker/node_modules/iobroker.freeathome/main.js:38:24)
host.homeserver | 2020-03-31 09:11:05.805 | error | Caught by controller[1]:     at Function.keys (<anonymous>)
host.homeserver | 2020-03-31 09:11:05.805 | error | Caught by controller[1]: (node:4319) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
freeathome.0 | 2020-03-31 09:11:05.136 | info | (4319) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
freeathome.0 | 2020-03-31 09:11:05.135 | info | (4319) terminating
freeathome.0 | 2020-03-31 09:11:05.105 | info | (4319) Got terminate signal TERMINATE_YOURSELF
 

`

**Comment by mobilutz** [comment]
@mabasger Thanks for the added logs.
Do you maybe have some more logs info? Maybe something before the last line `Got terminate signal TERMINATE_YOURSELF`

I am just asking, because I never saw this error.

Furthermore, what is the f@h system Version?

Thanks

**Comment by mabasger** [comment]
f@h is 2.4.0
`

freeathome.0 | 2020-03-31 10:55:17.235 | debug | (17004) state freeathome.0.info.connection changed: false (ack = true)
-- | -- | -- | --
freeathome.0 | 2020-03-31 10:55:17.229 | silly | (17004)  States user redis pmessage  freeathome.0.*/freeathome.0.info.connection:{"val":false,"ack":true,"ts":1585644917209,"q":0,"from":"system.adapter.freeathome.0","user":"system.user.admin","lc":158
freeathome.0 | 2020-03-31 10:55:17.217 | silly | (17004)  States system redis pmessage  system.adapter.freeathome.0.logLevel/system.adapter.freeathome.0.logLevel:{"val":"silly","ack":true,"ts":1585644917156,"q":0,"from":"system.adapter.freeathome.0","
freeathome.0 | 2020-03-31 10:55:17.167 | debug | (17004)  Could not connect to SysAp! - {"message":"getaddrinfo EAI_AGAIN  http:80","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN http:80\n     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.j
freeathome.0 | 2020-03-31 10:55:17.117 | info | (17004) Starting free@home API
freeathome.0 | 2020-03-31 10:55:17.076 | info | (17004) starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.freeathome, node: v8.16.0
host.homeserver | 2020-03-31 10:55:15.264 | info | instance system.adapter.luftdaten.0 terminated with code 0 (NO_ERROR)
host.homeserver | 2020-03-31 10:55:15.261 | info | Do not restart adapter system.adapter.freeathome.0 because desired by instance
host.homeserver | 2020-03-31 10:55:15.261 | error | instance  system.adapter.freeathome.0 terminated by request of the instance  itself and will not be restarted, before user restarts it.
luftdaten.0 | 2020-03-31 10:55:14.677 | info | (16976) Terminated (NO_ERROR): Without reason
freeathome.0 | 2020-03-31 10:55:14.598 | info | (16988) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
freeathome.0 | 2020-03-31 10:55:10.948 | debug | (16988) state freeathome.0.info.connection changed: false (ack = true)
freeathome.0 | 2020-03-31 10:55:10.935 | silly | (16988)  States user redis pmessage  freeathome.0.*/freeathome.0.info.connection:{"val":false,"ack":true,"ts":1585644910925,"q":0,"from":"system.adapter.freeathome.0","user":"system.user.admin","lc":158
freeathome.0 | 2020-03-31 10:55:10.917 | silly | (16988)  States system redis pmessage  system.adapter.freeathome.0.logLevel/system.adapter.freeathome.0.logLevel:{"val":"silly","ack":true,"ts":1585644910847,"q":0,"from":"system.adapter.freeathome.0","
freeathome.0 | 2020-03-31 10:55:10.875 | debug | (16988)  Could not connect to SysAp! - {"message":"getaddrinfo EAI_AGAIN  http:80","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN http:80\n     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.j
freeathome.0 | 2020-03-31 10:55:10.741 | info | (16988) Starting free@home API
freeathome.0 | 2020-03-31 10:55:10.620 | info | (16988) starting. Version 0.0.3 in /opt/iobroker/node_modules/iobroker.freeathome, node: v8.16.0
freeathome.0 | 2020-03-31 10:55:10.604 | warn | (16988) Got terminate signal. Checking desired PID: 17004 vs own PID 16988
freeathome.0 | 2020-03-31 10:55:10.603 | silly | (16988)  States system redis pmessage  system.adapter.freeathome.0.sigKill/system.adapter.freeathome.0.sigKill:{"val":17004,"ack":true,"ts":1585644910584,"q":0,"from":"system.host.homeserver","lc":15856
freeathome.0 | 2020-03-31 10:55:10.595 | warn | (16988) Got terminate signal. Checking desired PID: 0 vs own PID 16988
freeathome.0 | 2020-03-31 10:55:10.592 | silly | (16988)  States system redis pmessage  system.adapter.freeathome.0.sigKill/system.adapter.freeathome.0.sigKill:{"val":0,"ack":false,"ts":1585644910529,"q":0,"from":"system.host.homeserver","lc":15856449
freeathome.0 | 2020-03-31 10:55:10.604 | warn | (16988) Got terminate signal. Checking desired PID: 17004 vs own PID 16988
freeathome.0 | 2020-03-31 10:55:10.603 | silly | (16988) States system redis pmessage  system.adapter.freeathome.0.sigKill/system.adapter.freeathome.0.sigKill:{"val":17004,"ack":true,"ts":1585644910584,"q":0,"from":"system.host.homeserver","lc":1585
freeathome.0 | 2020-03-31 10:55:10.595 | warn | (16988) Got terminate signal. Checking desired PID: 0 vs own PID 16988
freeathome.0 | 2020-03-31 10:55:10.592 | silly | (16988) States system redis pmessage  system.adapter.freeathome.0.sigKill/system.adapter.freeathome.0.sigKill:{"val":0,"ack":false,"ts":1585644910529,"q":0,"from":"system.host.homeserver","lc":1585644
host.homeserver | 2020-03-31 10:55:10.584 | info | instance system.adapter.freeathome.0 started with pid 17004
host.homeserver | 2020-03-31 10:55:09.026 | info | stopInstance system.adapter.freeathome.0 killing pid 16988
freeathome.0 | 2020-03-31 10:55:08.629 | debug | (16988) statesDB connected
freeathome.0 | 2020-03-31 10:55:08.628 | debug | (16988) States connected to redis: 0.0.0.0:9000
freeathome.0 | 2020-03-31 10:55:08.408 | debug | (16988) States create System PubSub Client
freeathome.0 | 2020-03-31 10:55:08.404 | debug | (16988) States create User PubSub Client
freeathome.0 | 2020-03-31 10:55:08.329 | debug | (16988) Redis States: Use Redis connection: 0.0.0.0:9000
freeathome.0 | 2020-03-31 10:55:08.325 | debug | (16988) objectDB connected
freeathome.0 | 2020-03-31 10:55:08.313 | debug | (16988) Objects connected to redis: 0.0.0.0:9001
host.homeserver | 2020-03-31 10:55:08.024 | info | stopInstance system.adapter.freeathome.0 send kill signal
freeathome.0 | 2020-03-31 10:55:08.002 | debug | (16988) Objects client initialize lua scripts
freeathome.0 | 2020-03-31 10:55:08.001 | debug | (16988) Objects create User PubSub Client
host.homeserver | 2020-03-31 10:55:08.017 | info | stopInstance system.adapter.freeathome.0 (force=false, process=true)
freeathome.0 | 2020-03-31 10:55:07.999 | debug | (16988) Objects create System PubSub Client
freeathome.0 | 2020-03-31 10:55:07.858 | debug | (16988) Objects client ready ... initialize now
freeathome.0 | 2020-03-31 10:55:06.591 | debug | (16988) Redis Objects: Use Redis connection: 0.0.0.0:9001
luftdaten.0 | 2020-03-31 10:55:04.181 | info | (16976) starting. Version 0.0.11 in /opt/iobroker/node_modules/iobroker.luftdaten, node: v8.16.0
host.homeserver | 2020-03-31 10:55:04.161 | info | instance system.adapter.freeathome.0 started with pid 16988
host.homeserver | 2020-03-31 10:55:01.732 | info | instance system.adapter.freeathome.0 terminated with code 156 (156)
host.homeserver | 2020-03-31 10:55:01.731 | error | Caught by controller[1]: (node:16087) UnhandledPromiseRejectionWarning:  Unhandled promise rejection. This error originated either by throwing  inside of an async function without a catch block, or by
host.homeserver | 2020-03-31 10:55:01.730 | error | Caught by controller[1]:     at process._tickCallback (internal/process/next_tick.js:189:7)
host.homeserver | 2020-03-31 10:55:01.729 | error | Caught by controller[1]:     at <anonymous>
host.homeserver | 2020-03-31 10:55:01.728 | error | Caught by controller[1]:     at Freeathome.registerAllDevices (/opt/iobroker/node_modules/iobroker.freeathome/main.js:38:24)
host.homeserver | 2020-03-31 10:55:01.727 | error | Caught by controller[1]:     at Function.keys (<anonymous>)
host.homeserver | 2020-03-31 10:55:01.726 | error | Caught by controller[1]: (node:16087) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
freeathome.0 | 2020-03-31 10:55:01.040 | info | (16087) Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
freeathome.0 | 2020-03-31 10:55:01.039 | info | (16087) terminating
freeathome.0 | 2020-03-31 10:55:01.036 | info | (16087) Got terminate signal TERMINATE_YOURSELF
host.homeserver | 2020-03-31 10:55:01.026 | info | stopInstance system.adapter.freeathome.0 send kill signal

`

**Comment by mobilutz** [comment]
@mabasger Did you add the correct IP in the settings?
It looks as the connection cannot be made:
```
Could not connect to SysAp! - {"message":"getaddrinfo EAI_AGAIN http:80","name":"Error","stack":"Error: getaddrinfo EAI_AGAIN http:80\n at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.j
```

I will see, to have a better error handling for this in the future, I will add that to the ToDo #10

**Comment by mabasger** [comment]
The hostname is correct (http://192.168.1.xxx), 
HTTP API Settings is disabled (enabling makes no difference) and 
WS API Settings is disabled as well

**Comment by mobilutz** [comment]
This is the setup I have:
<img width="1144" alt="Screenshot 2020-03-31 at 11 02 59" src="https://user-images.githubusercontent.com/491877/78007930-42daf080-733f-11ea-8228-e6cc8d75fb7d.png">

Please only use the IP with the protocol in the hostname.

**Comment by mabasger** [comment]
![grafik](https://user-images.githubusercontent.com/14977978/78008248-bb41b180-733f-11ea-9e0b-9db98102068c.png)

**Comment by mabasger** [comment]
Sieht genauso aus :-(

**Comment by mobilutz** [comment]
Es kann daran liegen.
Ich werde heute abend nochmal schauen, wie genau es bei mir aussieht, und ich poste das dann mal.

**Comment by mabasger** [comment]
Es läuft mit node v10.15.2 - Danke!!!

**Comment by mobilutz** [comment]
I will close this ticket, but I will try to add the node version in the requirements
