### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by TheSpirit** [mobilutz/ioBroker.freeathome#70]
Hi.
I installed your adapter but the instance is not able to connect to free@home.
Here is the info of my system.
What could be the problem?
Thanks
![Bildschirmfoto 2020-04-27 um 21 24 42](https://user-images.githubusercontent.com/6056918/80412059-876d9380-88cd-11ea-8c85-2ac7c0e5c27b.png)

**Comment by mobilutz** [comment]
@TheSpirit Do you maybe have some infos, for example logs output?

I had a problem in the last couple of days, but after iobroker upgrade everything worked again.

**Comment by TheSpirit** [comment]
hi. this is the only info i get within iobroker log
![Bildschirmfoto 2020-04-28 um 10 58 27](https://user-images.githubusercontent.com/6056918/80468316-5037ca80-893f-11ea-9fbd-eef36e205698.png)

**Comment by mobilutz** [comment]
Maybe the settings for the SystemAccessPoint is not correct. Please check if the settings of the adapter are correct.

**Comment by TheSpirit** [comment]
what should be wrong?
i only have set ip, login name and password
the same credentials work fine within openhab
but i use openhab only for free@home and would like to switch to iobroker with all my iot
thanks

**Comment by TheSpirit** [comment]
any ideas what i can do?

**Comment by mobilutz** [comment]
There does not seem to be an obvious thing to be wrong. Maybe there is a whiteboard in the IP or so.

Please check if the settings you have look like this: https://github.com/mobilutz/ioBroker.freeathome/issues/56#issuecomment-606495530

**Comment by TheSpirit** [comment]
i read there, that the other one used node version 10.x
i am allready on 12.x
or is this not the nodejs version?
is my npm version ok?

**Comment by mobilutz** [comment]
IT could be, that the node 12.x does not work. I am also still running on node 10.x so I haven't tested the adapter under node 12.x

I will see to upgrade sometime and then I will take a deeper look into it.

**Comment by TheSpirit** [comment]
i just tried version 10.x but it still did not work

**Comment by mobilutz** [comment]
Then I think, that there is something not correct in the setup. Maybe an extra whitespace in the username, password or hostname?

**Comment by TheSpirit** [comment]
will set up a new user with only one character for username and password.
which privileges does the user need?

**Comment by TheSpirit** [comment]
one additional thing.
my system access point is still on 2.1.7
could this be the problem?

**Comment by TheSpirit** [comment]
created a new user with config options.
still no connection.
this is the silly log
![Bildschirmfoto 2020-05-04 um 12 13 24](https://user-images.githubusercontent.com/6056918/80956139-e2891400-8e00-11ea-98b8-6188ea5ebab8.png)
Does the "could not connect" mean ip is incorrect or user password is not correct?

**Comment by mobilutz** [comment]
What version of the SysAP are you running?

It seems that the IP is ok, but the login information is not correct.
You could try this package directly: https://github.com/henry-spanka/freeathome-api#readme
This is used here to connect to the SysAP.

**Comment by mobilutz** [comment]
Ah sorry, I didn't see this message: https://github.com/mobilutz/ioBroker.freeathome/issues/70#issuecomment-623355640

Yes, that is the problem.

From the package I liked above:
`It requires a System Access Point with version 2.3.1 or higher.`

**Comment by TheSpirit** [comment]
i just updated to 2.5 and it now works perfect with 12.16.3
i just implement it now within my loxone system.
if you need any help what the datapoints meen, feel free to ask.
allready helped with the datapoints for the binding for openhab.

**Comment by mobilutz** [comment]
Cool that the adapter is working with node 12.x :)

I will get back to you, once I have time to do something here ...
